### ISSUE TITLE
OutOfMemory exception in CatalogItem control

### ISSUE THREAD

**Issue by Alvaromah** [dotnet-architecture/eShopOnUWP#1]
When navigation from Main Catalog to an item detail and back to Main Catalog again for several times, a System.OutOfMemoryException is risen in OnLoad() control event.

Steps to repro:
1. Execute the App and go to Main Catalog.
2. Press an item to see it details.
3. Go back to Main Catalog.
4. Repeat steps 2 and 3 several times.

An exception of type System.OutOfMemoryException: 'Insufficient memory to continue the execution of the program.' is risen and the App exits unexpectedly.

**Comment by rido-min** [comment]
we are going to archive this project as deprecated. For a more up to date sample see https://github.com/Microsoft/InventorySample
