### ISSUE TITLE
Error when logout and login and close or open pane

### ISSUE THREAD

**Issue by Roberto2707** [dotnet-architecture/eShopOnUWP#11]
When logout and then login another time without close the app, when click on button to open or close the pane of navigationview, an error is fire.

**Comment by rido-min** [comment]
Hi @Roberto2707 I'm not able to reproduce this issue. Can you provide further details? Are you running the application from VS or Sideloading? Which version? 

Thanks for the feedback,
Rido

**Comment by Roberto2707** [comment]
Hello. I'm running the app in VS 2017 v.15.4.4
I run the app and login with default values, then I logout and re-login.
Then I push the close navigation button (IsPaneOpen) and receive the error:
System.ArgumentException: 'Value does not fall within the expected range.'
Another error occur when I run then app, then login and go to settings and
press the logout button. The error that I receive is:
System.Runtime.InteropServices.COMException: 'El identificador de operación
no es válido. (In english: The operation identificator is not valid).
Sorry for my english.
Thanks. Best regards.
Roberto.


2017-11-22 17:16 GMT+01:00 Ricardo Minguez (Rido) <notifications@github.com>
:

**Comment by Alvaromah** [comment]
Hi @Roberto2707,

We will release a new version in the next few days soon. This new version solve this and other issues.
You can check out this new version from the [dev branch](https://github.com/dotnet-architecture/eShopOnUWP/tree/dev).

Thanks again for your feedback.

Regards,

Alvaro

**Comment by rido-min** [comment]
we are going to archive this project as deprecated. For a more up to date sample see https://github.com/Microsoft/InventorySample
