### ISSUE TITLE
Project Update! Guide needed

### ISSUE THREAD

**Issue by odyright** [dotnet-architecture/eShopOnUWP#14]
Hello there, i tried to update the project to the last MvvMLight framework and WTS(windows template studio), everything worked but i got `Page not found:ViewModels.ShellViewModel. Did you forget to call NavigationService.Configure?`... after i signed in.

**Comment by rido-min** [comment]
we are going to archive this project as deprecated. For a more up to date sample see https://github.com/Microsoft/InventorySample
