### ISSUE TITLE
[FEEBACK] Possible improvements

### ISSUE THREAD

**Issue by SariDev** [dotnet-architecture/eShopOnUWP#8]
Hi everyone,

after I have talked to Cesar De la Torre on the .NET Blog he suggested that I should open a new issue here.

The .NET Blog post:
[https://blogs.msdn.microsoft.com/dotnet/2017/11/01/modernize-existing-net-apps-with-windows-containers-and-azure/#comments](url)

I like the project as it helps to get started building enterpries applications with microsofts UWP.

Following areas could be improved in my opninion:

1) Make the ViewModels portable
Right now the ViewModel classes depend on the UWP UI stack.
e.g. ShellViewModel is referencing Windows.UI namespaces.
Therefore VM’s are not portable to use them with other UI technologies.

I suggest to move ViewModels into a separate .NET Standard 2.0 project and abstract the UI dependencies away.
In general I personally try to put most of my code into .NET Standard projects as long as there is no real need for a platform specific dependency.

2) Use Dependency Injection instead of Service Location
In my opinion Dependency Injection is a cleaner way of resolving dependencies as a class must tell the consumer on which other classes it has a dependency on and the consumer must provide them in one way or another.
The class does not have to resolve it's dependencies by itself.
This makes passing mock implementations in unit tests easy.

With a Service Locator on the other side, the class has to resolve it's dependencies by itself (using the locator)

3) Show us how to extend the application (Modules / Extensions ...)
In classic .NET applications we can easily extend our applications as we have full access to Reflection API's.
As far as I know Assembly.Load( ) is not available for UWP applications.

[https://docs.microsoft.com/en-us/windows/uwp/launch-resume/extend-your-app-with-services-extensions-packages](url)
In-proc code plugins are only supported in C++ as it seems.
Will such scenarios be possible with c# in a future UWP release?

I think a sample on how to extend a UWP app would be great for this sample app.

Best regards

SariDev

**Comment by rido-min** [comment]
Hi @SariDev 

> 1 Make the ViewModels portable

We want to keep the project as simple as possible, trying to reduce the number of projects and assemblies unless there is a good reason to separate those. 

2> Use Dependency Injection instead of Service Location

The app has been created from Windows Template Studio, and we selected MVVMLight as one of the most popular MVVM frameworks, hence the use of the ViewModel Locator pattern. 
Do you know of any sample or framework that we can use as a reference to implement DI in UWP?

3> Show us how to extend the application (Modules / Extensions ...)

As you said, in-proc plugins scenarios are only supported in C++.
If this scenario is important for you I'd recommend to vote [this suggestion](https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/32220112-optional-package-in-proc-code-plug-ins-with-c-or) in UserVoice.

**Comment by SariDev** [comment]
Hi @rido-min,

> We want to keep the project as simple as possible, trying to reduce the number of projects and assemblies unless there is a good reason to separate those.

That's OK. 
I understand that.

> The app has been created from Windows Template Studio, and we selected MVVMLight as one of the most popular MVVM frameworks, hence the use of the ViewModel Locator pattern.
Do you know of any sample or framework that we can use as a reference to implement DI in UWP?

You could have a look at the [Template10](https://github.com/Windows-XAML/Template10/wiki/Bootstrapper#dependency-injection) Project over here on GitHub or at [Prism 
](https://github.com/Windows-XAML/Template10/wiki/Bootstrapper#dependency-injection)

I personally have no experience with both of them.

Another way could be to implement this by yourself.

Rough Description:
1. Instantiate a private DI Container in your app.xaml.cs
`container = new Container();`

2. Register your Interfaces with their respective implementations e.g. 
`container.Register<INavigationService, NavigationService>(Lifestyle.Singleton);`

3. Implement a NavigationService and pass a Container reference to the NavigationService.
`  public NavigationService(Frame hamburgerMenuRootFrame, Container container)
        {
            _hamburgerMenuRootFrame = hamburgerMenuRootFrame;
            _hamburgerMenuRootFrame.Navigated += _hamburgerMenuRootFrame_Navigated;
            _hamburgerMenuRootFrame.Navigating += _hamburgerMenuRootFrame_Navigating;
            _hamburgerMenuRootFrame.NavigationFailed += _hamburgerMenuRootFrame_NavigationFailed;
            _hamburgerMenuRootFrame.NavigationStopped += _hamburgerMenuRootFrame_NavigationStopped;
_pages = new ConcurrentDictionary<string, (Type view, Type viewModel)>();
            _container = container;
        }`

This is needed as the NavigationService must create the ViewModels for the DataContext of the Views to which it will navigated to.
```
/// <summary>
        /// Navigates to the submitted page and passes the parameter to it if necessary
        /// </summary>
        /// <param name="viewKey">The unique key that identifies the page</param>
        /// <param name="parameter">Parameters that are relevant for the target page</param>
        public void NavigateToView(string viewKey, object parameter = null)
        {
            if (!_pages.ContainsKey(viewKey))
            {
                throw new ArgumentException($"Page not found: {viewKey}. Did you forget to call NavigationService.Configure?", "pageKey");
            }

            // IMPORTANT: A UWP Frame creates a new instance of the page type on every navigation
            // A public parameterless constructor is required!
            // The datacontext (singleton vm instance managed by the container) must be added after navigation
            var viewType = _pages[viewKey].view;
            var navigationResult = _hamburgerMenuRootFrame.Navigate(viewType, parameter);

            if (navigationResult)
            {
                var vm = _container.GetInstance(_pages[viewKey].viewModel);
                if (_hamburgerMenuRootFrame.Content is Page page) page.DataContext = vm;
            }
        }
```

4. Tell the NavigationService which View and ViewModel type will be used for Navigation
`navigationService.Configure(Constants.MyPageKey, typeof(MyPage), typeof(IMyPageViewModel));`

Now every time you navigate to a view, a matching ViewModel will be retrieved by the Container and set as DataContext in the target view.
The dependencies of the ViewModels (constructor parameters) will be resolved by the Container if the types are also registered in the container.

> As you said, in-proc plugins scenarios are only supported in C++.
If this scenario is important for you I'd recommend to vote this suggestion in UserVoice.

Thanks for the link.
I will upvote that issue.

**Comment by rido-min** [comment]
we are going to archive this project as deprecated. For a more up to date sample see https://github.com/Microsoft/InventorySample
